### ISSUE TITLE
Parity-bitcoin: How to start the UI

### ISSUE THREAD

**Issue by lekanovic** [paritytech/parity-bitcoin#410]
Hi Parity,

I have manged to build the parity-bitcoin client, and I have been able start it and sync the blockchain. But I don't understand how to start the UI. I have previously used the parity client for Ethereum, where the UI is in the browser. Is this the same for parity-bitcoin, or there is not UI at the moment?

Thanks!

**Comment by debris** [comment]
parity-bitcoin does not have ui at the moment
