### ISSUE TITLE
Build instruction do not looks like they are working for me.

### ISSUE THREAD

**Issue by deadalnix** [paritytech/parity-bitcoin#411]
$ rustc --version
    rustc 1.16.0
    $ cargo --version
    cargo 0.15.0 (built 2016-11-26)
    $ cargo build -p pbtc --verbose
    [...]
    error[E0523]: found two different crates with name `std` that are not distinguished by differing `-C metadata`. This will result in symbol conflicts between the two.
      --> /home/deadalnix/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-0.9.13/src/lib.rs:13:1
       |
    13 | extern crate proc_macro;
       | ^^^^^^^^^^^^^^^^^^^^^^^^
    
    Build failed, waiting for other jobs to finish...
    error: Could not compile `serde_derive`.
    
    Caused by:
      process didn't exit successfully: `rustc /home/deadalnix/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-0.9.13/src/lib.rs --crate-name serde_derive --crate-type proc-macro -C prefer-dynamic -g -C metadata=5f13b2d16821e52b -C extra-filename=-5f13b2d16821e52b --out-dir /home/deadalnix/parity-bitcoin/target/debug/deps --emit=dep-info,link -L dependency=/home/deadalnix/parity-bitcoin/target/debug/deps --extern quote=/home/deadalnix/parity-bitcoin/target/debug/deps/libquote-a439d031a209fb07.rlib --extern serde_codegen_internals=/home/deadalnix/parity-bitcoin/target/debug/deps/libserde_codegen_internals-1fc4e4c8fbec0d43.rlib --extern syn=/home/deadalnix/parity-bitcoin/target/debug/deps/libsyn-16b7f313df67f289.rlib --cap-lints allow` (exit code: 101)

**Comment by debris** [comment]
You have very old version of cargo. Please try the latest one `cargo-0.17.0-nightly (f9e5481 2017-03-03)`.

**Comment by deadalnix** [comment]
I tried with the nightly version fo cargo and it does work. Case closed. Thanks.
