### ISSUE TITLE
Listening address is hardcoded to 127.0.0.1

### ISSUE THREAD

**Issue by infertux** [paritytech/parity-bitcoin#495]
https://github.com/paritytech/parity-bitcoin/blob/6db8c5e235c10988f7f52185c57db8629859360c/pbtc/commands/start.rs#L99

Any reason why pbtc is binding to 127.0.0.1 instead of 0.0.0.0? I'd like to allow incoming connections from the Internet.

Moreover, this doesn't respect `--only-net ipv6`.

**Comment by debris** [comment]
hah, true! feel free to open a pr and fix it! 👍

**Comment by infertux** [comment]
Ok I'm a Rust noob but I'll give it a try :)

**Comment by i1skn** [comment]
@debris @infertux 
What if we add a CLI option, like `--host`, with fallback to `0.0.0.0`. That would give a freedom to provide a custom IP address.

But here is the question:
. . . from `--help` :
```
--only-net <NET> Only connect to nodes in network version <NET> (ipv4 or ipv6).
```
So, if `--only-net` is `ipv6` - should `local_address` be as well? In this case, we need to validate `local_address` and have two fallbacks for `ipv4` and `ipv6`?

**Comment by 5chdn** [comment]
@i1skn sounds like a plan :)

**Comment by thackerronak** [comment]
How to allow outside IP?

**Comment by svyatonik** [comment]
@thackerronak This is an issue about accepting connections from other peers - you could pass `--host <your-external-ip-address>` cli arg to listen to specific interface or do not pass anything to keep listen on default interface. Based on your previous comments, I think you might be interested in listening for RPC requests from external nodes. In that case you could use `--jsonrpc-interface <your-external-ip-address>`.

**Comment by thackerronak** [comment]
@svyatonik I have set 0.0.0.0 in the jsonrpc interface. 
`curl -H 'content-type: application/json' --data-binary '{"jsonrpc": "2.0", "method": "getblockcount", "params": [], "id":1 }' localhost:18332`
Responce
`Provided Host header is not whitelisted.`
now how to whilelist host header?

**Comment by thackerronak** [comment]
Working with --jsonrpc-hosts=*
