### ISSUE TITLE
Invalid verification is_witness_commitment_script

### ISSUE THREAD

**Issue by defuz** [paritytech/parity-bitcoin#505]
From bip141:

> The commitment is recorded in a scriptPubKey of the coinbase transaction. **It must be at least 38 bytes**, with the first 6-byte of 0x6a24aa21a9ed

Current source state:

```rust
pub fn is_witness_commitment_script(script: &[u8]) -> bool {
	script.len() >= 36 &&
		script[0] == Opcode::OP_RETURN as u8 &&
		script[1] == 0x24 &&
		script[2] == 0xAA &&
		script[3] == 0x21 &&
		script[4] == 0xA9 &&
		script[5] == 0xED
}
```

It should be 38 here, not 36.

**Comment by svyatonik** [comment]
Thanks for the report, you're right. Will prepare a fix in a minute :)
