### ISSUE TITLE
CLI to import is broken

### ISSUE THREAD

**Issue by chevdor** [paritytech/parity-bitcoin#534]
Running this `$ target/release/pbtc import "/.../Bitcoin/testnet3/blocks/" `
returns the following error, which is legit: 
`You must select fork on first run: --btc, --bch`

But running:
`$ target/release/pbtc import "/.../Bitcoin/testnet3/blocks/" --btc` complains as well:
`error: Found argument '--btc' which wasn't expected, or isn't valid in this context`

**Comment by svyatonik** [comment]
Thanks for the report. The correct command line in your case should be:
`target/release/pbtc --btc --testnet import "/.../Bitcoin/testnet3/blocks/"`
I.e. order matters here - flags (`--btc` and `--testnet`) should come before subcommands (`import`).
