### ISSUE TITLE
SegWit bug stalls syncing

### ISSUE THREAD

**Issue by jlopp** [paritytech/parity-bitcoin#537]
I tried to sync this implementation with the --btc and --db-cache=24000 parameters.

Everything was going fine until I got to the SegWit activation block at height 481824. Then parity spit out:

> Block 0000000000000000001c8018d9cb3b742ef25114f27563e3fc4a1902167f9893 verification failed with error "WitnessInvalidNonceSize"

And every block after that resulted in: verification failed with error "Database(UnknownParent)" 

From what I can tell the above block is most certainly valid, so it looks like there's a consensus bug in this implementation.

**Comment by svyatonik** [comment]
Thank you for the report!
