### ISSUE TITLE
finishConnect(..) failed: Connection refused on Kubernetes Loadbalancer?

### ISSUE THREAD

**Issue by zeroFruit** [paritytech/parity-bitcoin#581]
I run parity bitcoin node on Kubernetes and assign external IP by using Loadbalancer.
When calling jsonrpc API to the node, I got the following errors.

## Request
```
curl --location --request POST 'http://<external-ip>' \
--header 'Content-Type: application/json' \
--data-raw '{
	"id":1,
	"jsonrpc": "2.0",
	"method": "getblockcount",
	"params": []
}'
```

## Error message
```
finishConnect(..) failed: Connection refused: <hostname>/10.0.1.101:18332
```

- I've tried port-forward pod of the node to the localhost, then it works fine.

**Comment by svyatonik** [comment]
I think by default we only expose RPC on localhost interface. Try specifying your external ip using `--jsonrpc-interface=<external-ip>` cli option
