### ISSUE TITLE
Issue Setting Fork on first run

### ISSUE THREAD

**Issue by ashaw1131** [paritytech/parity-bitcoin#588]
Commit Hash f635966521ac8f24ec7ef8c1c5bf29764644a825

`/pbtc`
You must select fork on first run: --btc, --bch

`./pbtc --btc`
Failed to start p2p module

**Comment by svyatonik** [comment]
Most probably that's because you have some other software (`bitcoind`?) listening on the same ports (8333/8332)

**Comment by ashaw1131** [comment]
@svyatonik NO,there is nothing running on those Ports
